platform :ios, '9.0'

target 'EmotionKeyboard' do
use_frameworks!

pod 'Alamofire'
pod 'AFNetworking'
pod 'YYModel'
pod 'Masonry'
pod 'SnapKit'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD',    '1.1.0'
pod 'TYPagerController'
pod 'SSZipArchive'
pod 'hpple'
pod 'pop'
pod 'FMDB'

#智齿石墨客服
#pod 'SobotKit'
#UM about
#pod 'UMCCommon'
#pod 'UMCSecurityPlugins'
#pod 'UMCCommonLog'
#pod 'UMCAnalytics'
#pod 'UMCErrorCatch'
# U-Share SDK UI模块（分享面板，建议添加）
#pod 'UMCShare/UI'
# 集成微信(精简版0.2M)
#pod 'UMCShare/Social/ReducedWeChat'
#UM GrowingIO
#pod 'GrowingAutoTrackKit'

#pod 'tingyunApp'

#   使用阿里百川等阿里系的 SDK 时，可能会出现冲突，所以通过引用没有UTDID的方式代替 pod 'Pingpp/Alipay'
#pod 'Pingpp/AlipayNoUTDID','~> 2.2.10'
#pod 'Pingpp/Wx', '~> 2.2.10'

#banner轮播
pod 'TYCyclePagerView'


end
